[package]
name = "waydapt"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
getopts = "0.2.21"
libc = "0.2.155"
quick-xml = "0.31.0"
shadow-rs = "0.32.0"
smallvec = "1.13.2"

[build-dependencies]
shadow-rs = "0.32.0"

[dependencies.rustix]
version = "0.38.34"
features = [
    "event",
    "fs",
    "net",
    "process",
]

[dependencies.nix]
version = "0.29.0"
features = [
    "process"
]
