[package]
name = "waydapt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
bumpalo = "3.16.0"
dlopen2 = "0.7.0"
getopts = "0.2.21"
libc = "0.2.155"
quick-xml = "0.31.0"
static_assertions = "1.1.0"


[dependencies.rustix]
version = "0.38.34"
features = [
    "event",
    "fs",
    "net",
    "process",
]

[dependencies.nix]
version = "0.29.0"
features = [
    "process"
]
