[package]
name = "waydapt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.16.0"
dlopen2 = "0.7.0"
quick-xml = "0.31.0"
static_assertions = "1.1.0"
