[package]
name = "waydapt"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
forking = ["dep:libc", "dep:nix"]
gitver = ["dep:shadow-rs"]
terminator = []
cleanup = []


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
getopts = "0.2.21"
libc = { version = "0.2.155", optional = true }
quick-xml = "0.31.0"
shadow-rs = { version = "0.32.0", optional = true }
smallvec = "1.13.2"

[build-dependencies]
shadow-rs = { version = "0.32.0", optional = true }

[dependencies.rustix]
version = "0.38.34"
features = [
    "event",
    "fs",
    "net",
    "process",
]

[dependencies.nix]
optional = true
version = "0.29.0"
features = [ "process" ]

[profile.release]
codegen-units = 1
lto = "fat"

[profile.small]
codegen-units = 1
inherits = "release"
opt-level = "z"
strip = true
debug-assertions = false
lto = "fat"

