[package]
name = "waydapt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.16.0"
ghost-cell = "0.2.6"
quick-xml = "0.31.0"
singleton-cell = "0.3.1"
singleton-trait = "0.3.0"
